---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 60m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.5.2'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: nginx-system
      interval: 10m
