version: '3'
services:
  bench:
    build: .
    command: go run main.go
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}