---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: argo-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argo-cd
  namespace: argo-system
spec:
  interval: 60m
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: argo-system
spec:
  interval: 3m
  install:
    crds: Skip
  upgrade:
    crds: Skip
  chart:
    spec:
      chart: argo-cd
      version: '5.43.3'
      sourceRef:
        kind: HelmRepository
        name: argo-cd
        namespace: argo-system
      interval: 10m
  values:
    ## Globally shared configuration
    global:
      image:
        repository: quay.io/argoproj/argocd
        tag: "v2.8.0"
        imagePullPolicy: IfNotPresent
    ## Server
    server:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - argocd.inulogic.binboum.eu
        tls:
        - hosts:
          - argocd.inulogic.binboum.eu
          secretName: argocd.inulogic.binboum.eu-tls
        https: true
    configs:
      cm:
        url: https://argocd.inulogic.binboum.eu/
        oidc.config: |
          name: sso
          issuer: https://lemur-5.cloud-iam.com/auth/realms/test-max
          clientID: argocd
          clientSecret: $oidc.keycloak.clientSecret
          requestedScopes: ["openid", "profile", "email", "groups"]
