apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fb-merge
  namespace: argo-system
spec:
  generators:
    - merge:
        mergeKeys:
          - repoName
          - branchName
        generators:
        - list:
            elements:
            - repoName: my-repo
              branchName: my-branch
            - repoName: my-repo
              branchName: my-other-branch
            - repoName: your-repo
              branchName: your-branch
        - plugin:
            configMapRef: cm-plugin
            name: plugin-merge
            params: # plugin should returns all existing keys without param
              repoName: my-repo
            requeueAfterSeconds: 10
  template:
    metadata:
      name: 'fb-merge-{{repoName}}-{{branchName}}'
    spec:
      source:
        repoURL: 'git@github.com:binboum/argo-test.git'
        targetRevision: 'HEAD'
        path: charts/app-client
        helm:
          releaseName: feature-test-merge-{{repoName}}-{{branchName}}
          valueFiles:
          - values.yaml
          values: |
            front:
              image: nginx:{{ tag }}
            back:
              image: nginx:latest
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'fb-test'
