apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fb-merge
  namespace: argo-system
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - repo
          - branch
        generators:
          - pullRequest:
              github:
                owner: binboum
                repo: argo-test
                labels:
                - preview
                tokenRef:
                  secretName: github-secret
                  key: token
              requeueAfterSeconds: 30
          - plugin:
              configMapRef: cm-plugin
              name: plugin-merge
              params:
                repo: "argo-test"
              requeueAfterSeconds: 10
  template:
    metadata:
      name: 'fb-merge-{{.branch}}'
    spec:
      source:
        repoURL: 'git@github.com:binboum/argo-test.git'
        targetRevision: 'HEAD'
        path: charts/app-client
        helm:
          releaseName: feature-test-merge-{{.branch}}
          valueFiles:
            - values.yaml
          values: |
            front:
              image: registry.inulogic.binboum.eu/argo-test/front:{{.branch}}@{{ .serviceData.digestFront }}
            back:
              image: registry.inulogic.binboum.eu/argo-test/back:{{.branch}}@{{ .serviceData.digestBack }}
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.branch}}"
