apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fb-matrix
  namespace: argo-system
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - pullRequest:
              github:
                owner: binboum
                repo: argo-test
                labels:
                - preview
                tokenRef:
                  secretName: github-secret
                  key: token
              requeueAfterSeconds: 30
          - plugin:
              configMapRef: cm-plugin
              name: plugin-matrix
              params:
                repoName: "argo-test"
                branchName: "{{.branch}}"
              requeueAfterSeconds: 10
  template:
    metadata:
      name: "fb-matrix-{{.repoName}}-{{.branchName}}"
    spec:
      source:
        repoURL: "git@github.com:binboum/argo-test.git"
        targetRevision: "HEAD"
        path: charts/app-client
        helm:
          releaseName: feature-test-matrix-{{.repoName}}-{{.branchName}}
          valueFiles:
            - values.yaml
          values: |
            front:
              image: nginx:{{.branchName}}@{{ .digestFront }}
            back:
              image: nginx:{{.branchName}}@{{ .digestBack }}
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.branchName}}"
