apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fb-plugin
  namespace: argo-system
spec:
  generators:
    - plugin:
        configMapRef: 
          name: cm-plugin
        inputParameters:
          repo: "my-repo"
          branch: "my-branch"
        requeueAfterSeconds: 86400
  template:
    metadata:
      name: "fb-plugin-{{repo}}-{{branch}}"
    spec:
      source:
        repoURL: "git@github.com:binboum/argo-test.git"
        targetRevision: "HEAD"
        path: charts/app-client
        helm:
          releaseName: feature-test-plugin-{{repo}}-{{branch}}
          valueFiles:
            - values.yaml
          values: |
            front:
              image: nginx:{{serviceData.tag}}
            back:
              image: nginx:latest
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: "fb-test"
