---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: wiremock-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wiremock
  namespace: wiremock-system
spec:
  interval: 60m
  url: https://gitkent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiremock
  namespace: wiremock-system
spec:
  interval: 5m
  chart:
    spec:
      chart: wiremock
      version: '0.1.3'
      sourceRef:
        kind: HelmRepository
        name: wiremock
        namespace: wiremock-system
      interval: 10m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - wiremock.inulogic.binboum.eu
      tls:
      - hosts:
        - wiremock.inulogic.binboum.eu
        secretName: wiremock.inulogic.binboum.eu